const products = {
    IA: [
        {
            name: "IB History Internal Assessment",
            title: 'To what extent was the collapse of collective security in European states during the Inter-war periods responsible for the development of Komi-san\'s character throughout season 2 of "Komi-san can\'t communicate"?',
            wordCount: 2191,
            level: 7,
            cost: 15.99,
        },
        {
            name: "IB Microeconomics Internal Assessment",
            title: "Why my parents are poor",
            wordCount: 797,
            level: 6,
            cost: 13.49,
        },
        {
            name: "IB Macroeconomics Internal Assessment",
            title: "Stock market crash of 1929 and it's impacts on childhood obesity",
            wordCount: 745,
            level: 5,
            cost: 12.99,
        },
        {
            name: "IB Geography Internal Assessment",
            title: "How volcanos are formed (idk how geography works)",
            wordCount: 2101,
            level: 7,
            cost: 16.99,
        },
        {
            name: "IB Chemistry Internal Assessment",
            title: "Investigation of the activation energy of sodium chloride and soy sauce",
            wordCount: 1997,
            level: 4,
            cost: 11.39,
        },
        {
            name: "IB Biology Internal Assessment",
            title: "Determining the physological attractiveness of a female based on the intensity of light reflected by her forehead",
            wordCount: 2199,
            level: 6,
            cost: 14.99,
        },
        {
            name: "IB Physics Internal Assessment",
            title: "Determining the coefficient of friction between cock and balls",
            wordCount: 2576,
            level: 7,
            cost: 15.99,
        },
        {
            name: "IB Math AA HL Internal Assessment",
            title: "Deriving the general expression for the gaussian transformation of balls",
            wordCount: 1567,
            level: 3,
            cost: 8.99,
        },
        {
            name: "IB Math AA SL Internal Assessment",
            title: "How to multiply fraction",
            wordCount: 256,
            level: 7,
            cost: 17.99,
        },
        {
            name: "English HL Essay",
            title: "The Destructive Pursuit of Idealism",
            worldCount: 1353,
            level: 5,
            cost: 12.99,
        }
    ],
    Core: [
        {
            name: "Mathematics Extended Essay",
            title: "Effectiveness of integrating piecewise functions with the Adaptive Simpson's method",
            rq: "How effective are solutions utilizing the Adaptive Simpson's method at integration a piecewise function made of semi-circles and tangent lines",
            wordCount: 3991,
            level: "D",
            cost: 13.49,
        },
        {
            name: "English Literature Extended Essay",
            title: "The Elegance of Trolling",
            rq: "How is the profound joy of trolling conveyed through 18th century English literature?",
            wordCount: 3562,
            level: "A",
            cost: 21.99,
        },
        {
            name: "History Extended Essay",
            title: "CBT: Fact or Fiction?",
            rq: "To what extent was CBT utilized by the Viet Cong as a means of interrogating American POWs during the Vietnam War?",
            wordCount: 3860,
            level: "B",
            cost: 18.49,
        },
        {
            name: "Economics Extended Essay",
            title: "Economics of embezzlement",
            rq: "To what extent does the corruption in the feet department account for the United States of America's increasing debt",
            wordCount: 3723,
            level: "C",
            cost: 16.99,
        },
        {
            name: "TOK Essay",
            title: "Can there be knowledge that is independent of culture?",
            rq: "",
            wordCount: 1583,
            level: "B",
            cost: 18.79,
        },
        {
            name: "TOK Essay",
            title: "Is there solid justification for regarding knowledge in the natural sciences more highly than another area of knowledge?",
            rq: "",
            wordCount: 1550,
            level: "A",
            cost: 20.49,
        },
        {
            name: "TOK Essay",
            title: 'To what extent do you agree with the claim that "there’s a world of difference between truth and facts".',
            rq: "",
            wordCount: 1595,
            level: "C",
            cost: 15.99,
        }
    ]
}
    export default products;